### PR TITLE
WIP – Adding some tests

### PR DESCRIPTION
**Pull request by j0k3r**
:construction:  **This is a work in progress.**

Just to let you know that I'll add some tests to your library.
I'll try to cleanup things too (like coding standard), mostly using `php-cs-fixer`.

What I've done:

- add travis & scrutinizer
- run `php-cs-fixer` to cleanup the code
- add missing exception (like `InvalidArgumentException`)
- `OAuth2` now take a `HttpClient` to avoid giving it in parameters of many of its methods (this simplify proxy method in `Client`)

Seeing what I've changed, I guess it'll be safer to release 2.0.0.

### CODE REVIEW

**Comment by Adyg** [comment]
Sure thing. Travis should be enabled now (fairly inexperienced with it, but please let me know if I missed anything).
 For Scrutinizer (https://scrutinizer-ci.com/), they only seem to have paid plans. If I'm correct about that, I'll have to skip for the time being. 

Cheers!

**Comment by j0k3r** [comment]
Travis is enabled, great!

Scrutinizer is free for open source project, you just need to create an account, link your Github account and then select your project.

> What about open-source repositories?
> We do not charge for open-source repositories, you can add as many as you like.

**Comment by Adyg** [comment]
Scrutinizer should also be enabled. Looks like a great tool.

**Comment by j0k3r** [comment]
I removed Pager classes but I was wondering how can they be used? It looks weird to me for the user to call `->api()` and give a pager.
How it is supposed to work with gallery for example?

**Comment by stefanzweifel** [comment]
Anyway we can merge this into master and tag it? Do you need any help?

**Comment by j0k3r** [comment]
Well, the test suite doesn't cover the API part (the folder) as of now.
Since @Adyg never answered my questions I didn't continue my work as of today.

**Comment by stefanzweifel** [comment]
Thanks for the heads up. Currently toying around with the package in [stefanzweifel/imgubox](https://github.com/stefanzweifel/imgubox) and the Pager confuses me, just like you.
I'll try to use your forked version. Maybe I can add some tests too :)

**Comment by j0k3r** [comment]
Testing the API is the hardest part :)
But I'm still waiting for @Adyg answer.

**Comment by j0k3r** [comment]
@Adyg :wave:  :point_up:

**Comment by j0k3r** [comment]
:point_right: @Adyg ?

**Comment by Adyg** [comment]
I don't have any spare time to handle this repo. Interested in taking it over, @j0k3r ?

**Comment by j0k3r** [comment]
Yep, I can try to find time to handle it :+1:

**Comment by Adyg** [comment]
Awesome, added you as collaborator. Let me know if you'd like a change of ownership (you'll have to remove your current fork before Github let's me change owners).

**Comment by j0k3r** [comment]
@Adyg I've removed my fork you can transfer ownership, thanks !

**Pull request closed without merging**
